=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::chatkit-threads-thread_id - Documentation for the /chatkit/threads/{thread_id} path.

=head1 DESCRIPTION

This document describes the API endpoint at C</chatkit/threads/{thread_id}>.

=head1 PATHS


=head2 C<DELETE /chatkit/threads/{thread_id}>

Delete ChatKit thread


Delete a ChatKit thread



=head3 Operation ID

C<DeleteThreadMethod>

    $client->DeleteThreadMethod( ... );

=head3 Parameters

=over 4

=item * C<thread_id> (in path) (Required) - Identifier of the ChatKit thread to delete.

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

Success


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):



=back

=head2 C<GET /chatkit/threads/{thread_id}>

Retrieve ChatKit thread


Retrieve a ChatKit thread



=head3 Operation ID

C<GetThreadMethod>

    $client->GetThreadMethod( ... );

=head3 Parameters

=over 4

=item * C<thread_id> (in path) (Required) - Identifier of the ChatKit thread to retrieve.

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

Success


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
       "created_at" : 1712345600,
       "id" : "cthr_def456",
       "object" : "chatkit.thread",
       "status" : {
          "type" : "active"
       },
       "title" : "Demo feedback",
       "user" : "user_456"
    }


=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut