=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::organization-projects-project_id-spend_alerts - Documentation for the /organization/projects/{project_id}/spend_alerts path.

=head1 DESCRIPTION

This document describes the API endpoint at C</organization/projects/{project_id}/spend_alerts>.

=head1 PATHS


=head2 C<GET /organization/projects/{project_id}/spend_alerts>

Lists project spend alerts.



=head3 Operation ID

C<list-project-spend-alerts>

    $client->list-project-spend-alerts( ... );

=head3 Parameters

=over 4

=item * C<project_id> (in path) (Required) - The ID of the project to inspect.

Type: C<string>



=item * C<limit> (in query) (Optional) - A limit on the number of spend alerts to return. Defaults to 20.

Type: C<integer>



=item * C<order> (in query) (Optional) - Sort order for the returned spend alerts.

Type: C<string>

Allowed values: C<asc, desc>


Default: C<asc>


=item * C<after> (in query) (Optional) - Cursor for pagination. Provide the ID of the last spend alert from the previous response to fetch the next page.

Type: C<string>



=item * C<before> (in query) (Optional) - Cursor for pagination. Provide the ID of the first spend alert from the previous response to fetch the previous page.

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

Project spend alerts listed successfully.


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
       "data" : [
          "{\n    \"id\": \"alert_abc123\",\n    \"object\": \"project.spend_alert\",\n    \"threshold_amount\": 100000,\n    \"currency\": \"USD\",\n    \"interval\": \"month\",\n    \"notification_channel\": {\n        \"type\": \"email\",\n        \"recipients\": [\"finance@example.com\"],\n        \"subject_prefix\": \"OpenAI spend alert\"\n    }\n}\n"
       ]
    }


=back

=head2 C<POST /organization/projects/{project_id}/spend_alerts>

Creates a project spend alert.



=head3 Operation ID

C<create-project-spend-alert>

    $client->create-project-spend-alert( ... );

=head3 Parameters

=over 4

=item * C<project_id> (in path) (Required) - The ID of the project to update.

Type: C<string>



=back

=head3 Request Body
  
=head3 Content Type: C<application/json>

    
      Parameters for creating or updating a spend alert.

      
      
Example:

    {
       "notification_channel" : {
          "recipients" : [
             null
          ]
       }
    }


             

=head3 Responses


=head4 Status Code: C<200>

Project spend alert created successfully.


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
        "id": "alert_abc123",
        "object": "project.spend_alert",
        "threshold_amount": 100000,
        "currency": "USD",
        "interval": "month",
        "notification_channel": {
            "type": "email",
            "recipients": ["finance@example.com"],
            "subject_prefix": "OpenAI spend alert"
        }
    }


=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut