=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::organization-projects-project_id-service_accounts-service_account_id-api_keys - Documentation for the /organization/projects/{project_id}/service_accounts/{service_account_id}/api_keys path.

=head1 OPERATIONS

=head2 POST /organization/projects/{project_id}/service_accounts/{service_account_id}/api_keys

=head3 CreateanAPIkeyforaserviceaccount

  $client->createan_ap_ikeyforaserviceaccount({
      body => { ... },
  });

Creates an API key for a service account in the project.

=head4 Path/query parameters

=over

=item * C<project_id> (in path, required, string) - The ID of the project.

=item * C<service_account_id> (in path, required, string) - The ID of the service account.

=back

=head4 Responses

B<200 - Service account API key created successfully.>

Content-Type: application/json

Example:

    {
       "created_at" : 0,
       "id" : "string",
       "name" : "string",
       "object" : "organization.project.service_account.api_key",
       "value" : "string"
    }

=head1 SCHEMAS

=head2 CreateProjectServiceAccountApiKeyBody

Properties:

=over

=item * C<name> (string) - API key name.

=item * C<scopes> (array of string) - API key scopes.

=back

=head2 ServiceAccountApiKeyBody

Properties:

=over

=item * C<created_at> (integer, required) - The Unix timestamp (in seconds) when the API key was created.

=item * C<id> (string, required) - The identifier of the API key.

=item * C<name> (string, required) - The name of the API key.

=item * C<object> (string, required) - The object type, which is always
C<organization.project.service_account.api_key>

Allowed values: organization.project.service_account.api_key

Default: organization.project.service_account.api_key

=item * C<value> (string, required) - The unredacted API key value.

=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut
