=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::organization-groups-group_id-roles-role_id - Documentation for the /organization/groups/{group_id}/roles/{role_id} path.

=head1 DESCRIPTION

This document describes the API endpoint at C</organization/groups/{group_id}/roles/{role_id}>.

=head1 PATHS


=head2 C<DELETE /organization/groups/{group_id}/roles/{role_id}>

Unassign organization role from group


Unassigns an organization role from a group within the organization.



=head3 Operation ID

C<unassign-group-role>

    $client->unassign-group-role( ... );

=head3 Parameters

=over 4

=item * C<group_id> (in path) (Required) - The ID of the group to modify.

Type: C<string>



=item * C<role_id> (in path) (Required) - The ID of the organization role to remove from the group.

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

Organization role unassigned from the group successfully.


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
        "object": "group.role.deleted",
        "deleted": true
    }


=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut