=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::organization-groups - Documentation for the /organization/groups path.

=head1 DESCRIPTION

This document describes the API endpoint at C</organization/groups>.

=head1 PATHS


=head2 C<GET /organization/groups>

List groups


Lists all groups in the organization.



=head3 Operation ID

C<list-groups>

    $client->list-groups( ... );

=head3 Parameters

=over 4

=item * C<limit> (in query) (Optional) - A limit on the number of groups to be returned. Limit can range between 0 and 1000, and the default is 100.


Type: C<integer>


Default: C<100>


=item * C<after> (in query) (Optional) - A cursor for use in pagination. `after` is a group ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with group_abc, your subsequent call can include `after=group_abc` in order to fetch the next page of the list.


Type: C<string>



=item * C<order> (in query) (Optional) - Specifies the sort order of the returned groups.

Type: C<string>

Allowed values: C<asc, desc>


Default: C<asc>


=back


=head3 Responses


=head4 Status Code: C<200>

Groups listed successfully.


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
        "object": "list",
        "data": [
            {
                "id": "group_01J1F8ABCDXYZ",
                "name": "Support Team",
                "created_at": 1711471533,
                "is_scim_managed": false
            },
            {
                "id": "group_01J1F8PQRMNO",
                "name": "Sales",
                "created_at": 1711472599,
                "is_scim_managed": true
            }
        ],
        "has_more": false,
        "next": null
    }


=back

=head2 C<POST /organization/groups>

Create group


Creates a new group in the organization.



=head3 Operation ID

C<create-group>

    $client->create-group( ... );

=head3 Parameters

=over 4

=back

=head3 Request Body
  
=head3 Content Type: C<application/json>

    
      Request payload for creating a new group in the organization.

      
      
Example:

    "{\n    \"name\": \"Support Team\"\n}\n"


             

=head3 Responses


=head4 Status Code: C<200>

Group created successfully.


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
        "id": "group_01J1F8ABCDXYZ",
        "name": "Support Team",
        "created_at": 1711471533,
        "is_scim_managed": false
    }


=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut