=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::realtime-translations-client_secrets - Documentation for the /realtime/translations/client_secrets path.

=head1 DESCRIPTION

This document describes the API endpoint at C</realtime/translations/client_secrets>.

=head1 PATHS


=head2 C<POST /realtime/translations/client_secrets>

Create a Realtime translation client secret with an associated translation session configuration.

Client secrets are short-lived tokens that can be passed to a client app,
such as a web frontend or mobile client, which grants access to the Realtime
Translation API without leaking your main API key. You can configure a custom
TTL for each client secret.

Returns the created client secret and the effective translation session object.
The client secret is a string that looks like C<ek_1234>.



=head3 Operation ID

C<create-realtime-translation-client-secret>

    $client->create-realtime-translation-client-secret( ... );

=head3 Parameters

=over 4

=back

=head3 Request Body
  
=head3 Content Type: C<application/json>

    
      Create a translation session and client secret for the Realtime API.


      
      
Example:

    {
       "expires_after" : null,
       "session" : {
          "audio" : {
             "input" : null,
             "output" : null
          }
       }
    }


             

=head3 Responses


=head4 Status Code: C<200>

Translation client secret created successfully.


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
      "value": "ek_68af296e8e408191a1120ab6383263c2",
      "expires_at": 1756310470,
      "session": {
        "id": "sess_C9CiUVUzUzYIssh3ELY1d",
        "type": "translation",
        "expires_at": 1756310470,
        "model": "gpt-realtime-translate",
        "audio": {
          "input": {
            "transcription": null,
            "noise_reduction": null
          },
          "output": {
            "language": "es"
          }
        }
      }
    }


=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut