=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::realtime-calls-call_id-hangup - Documentation for the /realtime/calls/{call_id}/hangup path.

=head1 DESCRIPTION

This document describes the API endpoint at C</realtime/calls/{call_id}/hangup>.

=head1 PATHS


=head2 C<POST /realtime/calls/{call_id}/hangup>

End an active Realtime API call, whether it was initiated over SIP or
WebRTC.



=head3 Operation ID

C<hangup-realtime-call>

    $client->hangup-realtime-call( ... );

=head3 Parameters

=over 4

=item * C<call_id> (in path) (Required) - The identifier for the call. For SIP calls, use the value provided in the
[`realtime.call.incoming`](/docs/api-reference/webhook-events/realtime/call/incoming)
webhook. For WebRTC sessions, reuse the call ID returned in the `Location`
header when creating the call with
[`POST /v1/realtime/calls`](/docs/api-reference/realtime/create-call).

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

Call hangup initiated successfully.


=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut