=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::realtime-client_secrets - Documentation for the /realtime/client_secrets path.

=head1 DESCRIPTION

This document describes the API endpoint at C</realtime/client_secrets>.

=head1 PATHS


=head2 C<POST /realtime/client_secrets>

Create a Realtime client secret with an associated session configuration.

Client secrets are short-lived tokens that can be passed to a client app,
such as a web frontend or mobile client, which grants access to the Realtime API without
leaking your main API key. You can configure a custom TTL for each client secret.

You can also attach session configuration options to the client secret, which will be
applied to any sessions created using that client secret, but these can also be overridden
by the client connection.

L<Learn more about authentication with client secrets over WebRTC|https://platform.openai.com/docs/guides/realtime-webrtc>.

Returns the created client secret and the effective session object. The client secret is a string that looks like C<ek_1234>.



=head3 Operation ID

C<create-realtime-client-secret>

    $client->create-realtime-client-secret( ... );

=head3 Parameters

=over 4

=back

=head3 Request Body
  
=head3 Content Type: C<application/json>

    
      Create a session and client secret for the Realtime API. The request can specify
either a realtime or a transcription session configuration.
[Learn more about the Realtime API](/docs/guides/realtime).


      
      
Example:

    {
       "expires_after" : null
    }


             

=head3 Responses


=head4 Status Code: C<200>

Client secret created successfully.


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
      "value": "ek_68af296e8e408191a1120ab6383263c2",
      "expires_at": 1756310470,
      "session": {
        "type": "realtime",
        "object": "realtime.session",
        "id": "sess_C9CiUVUzUzYIssh3ELY1d",
        "model": "gpt-realtime-2025-08-25",
        "output_modalities": [
          "audio"
        ],
        "instructions": "You are a friendly assistant.",
        "tools": [],
        "tool_choice": "auto",
        "max_output_tokens": "inf",
        "tracing": null,
        "truncation": "auto",
        "prompt": null,
        "expires_at": 0,
        "audio": {
          "input": {
            "format": {
              "type": "audio/pcm",
              "rate": 24000
            },
            "transcription": null,
            "noise_reduction": null,
            "turn_detection": {
              "type": "server_vad",
              "threshold": 0.5,
              "prefix_padding_ms": 300,
              "silence_duration_ms": 200,
              "idle_timeout_ms": null,
              "create_response": true,
              "interrupt_response": true
            }
          },
          "output": {
            "format": {
              "type": "audio/pcm",
              "rate": 24000
            },
            "voice": "alloy",
            "speed": 1.0
          }
        },
        "include": null
      }
    }


=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut