=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::responses-compact - Documentation for the /responses/compact path.

=head1 DESCRIPTION

This document describes the API endpoint at C</responses/compact>.

=head1 PATHS


=head2 C<POST /responses/compact>

Compact a conversation. Returns a compacted response object.

Learn when and how to compact long-running conversations in the L<conversation state guide|https://platform.openai.com/docs/guides/conversation-state#managing-the-context-window>. For ZDR-compatible compaction details, see L<Compaction (advanced)|https://platform.openai.com/docs/guides/conversation-state#compaction-advanced>.



=head3 Operation ID

C<Compactconversation>

    $client->Compactconversation( ... );

=head3 Parameters

=over 4

=back

=head3 Request Body
  
=head3 Content Type: C<application/json>

    
      

      
             
=head3 Content Type: C<application/x-www-form-urlencoded>

    
      

      
             

=head3 Responses


=head4 Status Code: C<200>

Success


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
       "created_at" : 1731459200,
       "id" : "resp_001",
       "object" : "response.compaction",
       "output" : [
          {
             "content" : [
                {
                   "text" : "Summarize our launch checklist from last week.",
                   "type" : "input_text"
                }
             ],
             "role" : "user",
             "type" : "message"
          },
          {
             "content" : [
                {
                   "text" : "You are performing a CONTEXT CHECKPOINT COMPACTION...",
                   "type" : "input_text"
                }
             ],
             "role" : "user",
             "type" : "message"
          },
          {
             "encrypted_content" : "encrypted-summary",
             "id" : "cmp_001",
             "type" : "compaction"
          }
       ],
       "usage" : {
          "input_tokens" : 42897,
          "output_tokens" : 12000,
          "total_tokens" : 54912
       }
    }


=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut