=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::skills-skill_id-versions - Documentation for the /skills/{skill_id}/versions path.

=head1 DESCRIPTION

This document describes the API endpoint at C</skills/{skill_id}/versions>.

=head1 PATHS


=head2 C<GET /skills/{skill_id}/versions>

List skill versions for a skill.



=head3 Operation ID

C<ListSkillVersions>

    $client->ListSkillVersions( ... );

=head3 Parameters

=over 4

=item * C<skill_id> (in path) (Required) - The identifier of the skill.

Type: C<string>



=item * C<limit> (in query) (Optional) - Number of versions to retrieve.

Type: C<integer>



=item * C<order> (in query) (Optional) - Sort order of results by version number.

Type: C<string>

Allowed values: C<asc, desc>



=item * C<after> (in query) (Optional) - The skill version ID to start after.

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

Success


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
       "data" : [
          null
       ]
    }


=back

=head2 C<POST /skills/{skill_id}/versions>

Create a new immutable skill version.



=head3 Operation ID

C<CreateSkillVersion>

    $client->CreateSkillVersion( ... );

=head3 Parameters

=over 4

=item * C<skill_id> (in path) (Required) - The identifier of the skill to version.

Type: C<string>



=back

=head3 Request Body
  
=head3 Content Type: C<application/json>

    
      Uploads a new immutable version of a skill.

      
             
=head3 Content Type: C<multipart/form-data>

    
      Uploads a new immutable version of a skill.

      
             

=head3 Responses


=head4 Status Code: C<200>

Success


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):



=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut