=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::skills-skill_id-versions-version - Documentation for the /skills/{skill_id}/versions/{version} path.

=head1 DESCRIPTION

This document describes the API endpoint at C</skills/{skill_id}/versions/{version}>.

=head1 PATHS


=head2 C<DELETE /skills/{skill_id}/versions/{version}>

Delete a skill version.



=head3 Operation ID

C<DeleteSkillVersion>

    $client->DeleteSkillVersion( ... );

=head3 Parameters

=over 4

=item * C<skill_id> (in path) (Required) - The identifier of the skill.

Type: C<string>



=item * C<version> (in path) (Required) - The skill version number.

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

Success


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):



=back

=head2 C<GET /skills/{skill_id}/versions/{version}>

Get a specific skill version.



=head3 Operation ID

C<GetSkillVersion>

    $client->GetSkillVersion( ... );

=head3 Parameters

=over 4

=item * C<skill_id> (in path) (Required) - The identifier of the skill.

Type: C<string>



=item * C<version> (in path) (Required) - The version number to retrieve.

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

Success


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):



=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut