=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::videos-characters - Documentation for the /videos/characters path.

=head1 DESCRIPTION

This document describes the API endpoint at C</videos/characters>.

=head1 PATHS


=head2 C<POST /videos/characters>

Create a character from an uploaded video.



=head3 Operation ID

C<CreateVideoCharacter>

    $client->CreateVideoCharacter( ... );

=head3 Parameters

=over 4

=back

=head3 Request Body
  
=head3 Content Type: C<multipart/form-data>

    
      Parameters for creating a character from an uploaded video.

      
             

=head3 Responses


=head4 Status Code: C<200>

Success


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):



=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut